### ISSUE TITLE
GetBulksAsync returns Data as null

### ISSUE THREAD

**Issue by numanPtr** [EodHistoricalData/EODHistoricalData.Wrapper#2]
```csharp
await _eodApi.GetBulksAsync("US", null, null, "MSFT.US,AAPL.US")
```
Returns the count as 2 but Data object is null for all elements. Looks like a casting/conversion issue.

**Comment by deios0** [comment]
Hello, actually it's because you get data in CSV, please change the format to JSON and everything will work.

**Comment by numanPtr** [comment]
@deios0 Where does the API provide me with the option to select format?
If I understand it correctly this entire wrapper in most cases uses fmt=json!
See: [This line](https://github.com/EodHistoricalData/EODHistoricalData.Wrapper/blob/467147d6e524696c798f023185b3d9d9b5abeeaa/EODHistoricalData.Wrapper/APIs/BulkAPI.cs#L12) it already has fmt=json!
