### ISSUE TITLE
Cash_FlowData Filing_date

### ISSUE THREAD

**Issue by ElDuderinoBerlin** [EodHistoricalData/EODHistoricalData.Wrapper#26]
Hi,

why are Date + Filing_date of Cash_FlowData strings and not a DateTimes?

Regards

**Comment by nicethatcher** [comment]
Hello,

please note that these strings are private.
`private string DateJSON { get; set; }`
`private string Filing_dateJSON { get; set; }`

I assume that you will be interested in public DateTime? Date + Filling_date.
`public DateTime? Date { get => GetDate.ParseDate(DateJSON); }`
`public DateTime? Filing_date { get => GetDate.ParseDate(Filing_dateJSON); }`
