### ISSUE TITLE
GetBulksAsync JSON deserialization fails, all Data elements are null!

### ISSUE THREAD

**Issue by numanPtr** [EodHistoricalData/EODHistoricalData.Wrapper#3]
See the screenshot:
![image](https://user-images.githubusercontent.com/93382569/178984972-1c8f60dd-0aa8-4083-8b6b-ed2bc7c24618.png)

This is what I was referring to in issue #2. See this [comment as well](https://github.com/EodHistoricalData/EODHistoricalData.Wrapper/issues/2#issuecomment-1181667274). The format of data is JSON.

The assert in unit test just checks for the result to be not null, but doesn't bother if there actually is any content in the result or not!

**Comment by mdufour8** [comment]
Note that I get the same same error with the null value using the GetExtendedBulkAsync function call.

**Comment by mdufour8** [comment]
I manage to fix the issue by creating my own function for download and changing the internal interface definition to match the download result. The name currently to not match so that nothing is written in the structure:

My new interface data definition is 👍 

public class BulkData
{
    public string code { get; set; }
    public string exchange_short_name { get; set; }
    public DateTime? date { get; set; }
    public double? open { get; set; }
    public double? high { get; set; }
    public double? low { get; set; }
    public double? close { get; set; }
    public double? adjusted_Close { get; set; }
    public long? volume { get; set; }
    public double? prev_close { get; set; }
    public double? change { get; set; }
    public double? change_p { get; set; }
}

compare to the actual one that is:

{
    public class Data
    {
        public string? Code { get; set; }

        public string? ExchangeShortName { get; set; }

        public DateTime? Date { get; set; }

        public double? Open { get; set; }

        public double? High { get; set; }

        public double? Low { get; set; }

        public double? Close { get; set; }

        public double? AdjustedClose { get; set; }

        public long? Volume { get; set; }

        public double? PrevClose { get; set; }

        public double? Change { get; set; }

        public double? ChangeP { get; set; }
    }
}

**Comment by deios0** [comment]
Thank you for letting us know, we will check it on our end also.
