### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pratyak1** [EodHistoricalData/EODHistoricalData.Wrapper#4]
The ExchangeDetails has a dictionary for ExchangeHolidays and the property has no doc comment. What does the dictionary key stand for? 

[ExchangeHolidays ](https://github.com/EodHistoricalData/EODHistoricalData.Wrapper/blob/master/EODHistoricalData.Wrapper/Model/ExchageDetails/ExchangeDetail.cs)

**Comment by nicethatcher** [comment]
fixed on the API side
