### ISSUE TITLE
Fundamentals data parsing is broken because of flawed date data

### ISSUE THREAD

**Issue by daleholborow** [EodHistoricalData/EODHistoricalData.Wrapper#7]
When querying using GetFundamentalDataAsync method, for stock ticker GN1.IR, the json contains faulty date data and so the parsing throws exceptions:

Could not convert string to DateTime: 0000-00-00. Path 'Highlights.MostRecentQuarter', line 1, position 1478.

Seems that either the API data needs fixing (preferably), or the C# logic parsing needs to be improved to cater for these flawed date values.

**Comment by daleholborow** [comment]
Hi. When will the nuget pacakges be updated to reflect these latest changes?

**Comment by nicethatcher** [comment]
> Hi. When will the nuget pacakges be updated to reflect these latest changes?

Hello, changes have been made to the nuget package, sorry for the delay
